apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
helmCharts:
  - name: kyverno
    repo: https://kyverno.github.io/kyverno/
    includeCRDs: true
    releaseName: kyverno-operator
    version: 3.0.2
    valuesInline:
      config:
        resourceFiltersExcludeNamespaces:
          - "kube-system"
    namespace: kyverno
