apiVersion: microgateway.airlock.com/v1alpha1
kind: HeaderRewrites
metadata:
  name: template
spec:
  request:
    allow:
      matchingHeaders:
        builtIn:
          standardHeaders: true
        custom:
          - name: Allow additional request header
            headers:
              - name:
                  matcher:
                    exact: Accept-Auth
              - name:
                  matcher:
                    exact: Depth
              - name:
                  matcher:
                    exact: Destination
              - name:
                  matcher:
                    exact: If
              - name:
                  matcher:
                    exact: Lock-Token
              - name:
                  matcher:
                    exact: Overwrite
              - name:
                  matcher:
                    exact: Timeout
              - name:
                  matcher:
                    exact: translate
              - name:
                  matcher:
                    exact: X-FeatureVersion
              - name:
                  matcher:
                    exact: X-IDCRL_ACCEPTED
              - name:
                  matcher:
                    exact: X-IDCRL_OPTIONS
              - name:
                  matcher:
                    exact: X-MSGETWEBURL
              - name:
                  matcher:
                    exact: X-MS-CookieUri-Requested
              - name:
                  matcher:
                    exact: X-Office-Major-Version
              - name:
                  matcher:
                    exact: Content-Length
    remove:
      builtIn:
        alternativeForwardedHeaders: true
  response:
    add:
      builtIn:
        csp: true
        featurePolicy: true
        hsts: true
        hstsPreload: false
        referrerPolicy: true
        xContentTypeOptions: true
        xFrameOptions: true
    allow:
      matchingHeaders:
        builtIn:
          standardHeaders: false
    remove:
      builtIn:
        auth:
          basic: false
          negotiate: true
          ntlm: true
        permissiveCors: true