apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sidecargateway.yaml
  - contentsecurity.yaml
  - headerrewrites.yaml
  - denyrules.yaml

commonLabels:
  app.kubernetes.io/template-version: 1.0.1
  app.kubernetes.io/version: 4.0.0
  app.kubernetes.io/component: airlock-microgateway