apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: airlock-microgateway-operator
    app.kubernetes.io/version: 4.1.7
  name: airlock-microgateway-operator-envoyhttpfilter-editor
rules:
  - apiGroups:
      - microgateway.airlock.com
    resources:
      - envoyhttpfilters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - microgateway.airlock.com
    resources:
      - envoyhttpfilters/status
    verbs:
      - get
