apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: airlock-microgateway-operator
    app.kubernetes.io/version: 4.0.0
  name: airlock-microgateway-operator-envoyconfiguration-viewer
rules:
  - apiGroups:
      - microgateway.airlock.com
    resources:
      - envoyconfigurations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - microgateway.airlock.com
    resources:
      - envoyconfigurations/status
    verbs:
      - get
