apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: airlock-microgateway-operator
    app.kubernetes.io/version: 4.0.2
  name: airlock-microgateway-operator-sidecargateway-viewer
rules:
  - apiGroups:
      - microgateway.airlock.com
    resources:
      - sidecargateways
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - microgateway.airlock.com
    resources:
      - sidecargateways/status
    verbs:
      - get
