apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: airlock-microgateway-operator
    app.kubernetes.io/version: 4.1.7
  name: airlock-microgateway-operator-contentsecurity-editor
rules:
  - apiGroups:
      - microgateway.airlock.com
    resources:
      - contentsecurities
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
