apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: airlock-microgateway-operator
    app.kubernetes.io/version: 4.1.4
  name: airlock-microgateway-operator-denyrules-viewer
rules:
  - apiGroups:
      - microgateway.airlock.com
    resources:
      - denyrules
    verbs:
      - get
      - list
      - watch
