apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-insecure-denyrules
  annotations:
    policies.kyverno.io/title: Disallow insecure DenyRules
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: high
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.20"
    policies.kyverno.io/subject: DenyRules
    policies.kyverno.io/description: >-
      Description: Disallow insecure DenyRules settings for 'threatHandlingMode', security 'level', ...
      Contact:     security@company.com
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: disallow-insecure-threatHandlingMode
      match:
        any:
          - resources:
              kinds:
                - microgateway.airlock.com/v1alpha1/DenyRules
      preconditions:
        all:
          - key: "{{ request.operation || 'BACKGROUND' }}"
            operator: NotEquals
            value: DELETE
      validate:
        message: >-
          DenyRules with 'threatHandlingMode' other than 'block' is not allowed.
        deny:
          conditions:
            all:
              - key: "{{ request.object.spec.request.builtIn.settings.threatHandlingMode }}"
                operator: AnyNotIn
                value:
                  - block
    - name: disallow-denyRules-with-insecure-security-level
      match:
        any:
          - resources:
              kinds:
                - microgateway.airlock.com/v1alpha1/DenyRules
      preconditions:
        all:
          - key: "{{ request.operation || 'BACKGROUND' }}"
            operator: NotEquals
            value: DELETE
      validate:
        message: >-
          DenyRules with 'level' other than 'standard' or 'strict' is not allowed.
        deny:
          conditions:
            all:
              - key: "{{ request.object.spec.request.builtIn.settings.level }}"
                operator: AnyNotIn
                value:
                  - standard
                  - strict
