apiVersion: v2
name: airlock-microgateway-operator-helm
description: A Helm chart for deploying the Airlock Microgateway
type: application
home: https://www.airlock.com/en/microgateway
version: "4.2.0-alpha1"
appVersion: "4.2.0-alpha1"
annotations:
  charts.openshift.io/name: Airlock Microgateway
keywords:
  - WAF
  - Web Application Firewall
  - WAAP
  - Web Application and API protection
  - OWASP
  - Airlock
  - Microgateway
  - Security
  - Filtering
  - DevSecOps
  - shift left
maintainers:
  - email: support@airlock.com
    name: Airlock
