apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airlock-microgateway-operator-proxy-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: airlock-microgateway-operator-proxy-ns
subjects:
  - kind: ServiceAccount
    name: airlock-microgateway-operator-controller-manager
