apiVersion: v1
data:
  statsd.yaml: |
    mappings:
    # Config loading metrics
    - match: "ratelimit.service.config_load_success"
      name: "airlock_microgateway_license_guard_config_load_success_total"
      match_metric_type: counter
      help: "Number of times the xDS configuration was successfully updated."

    - match: "ratelimit.service.config_load_error"
      name: "airlock_microgateway_license_guard_config_load_error_total"
      match_metric_type: counter
      help: "Number of times the xDS configuration update failed."

    # Server metrics
    - match: "ratelimit_server.ShouldRateLimit.total_requests"
      name: "airlock_microgateway_license_guard_grpc_ratelimit_requests_total"
      match_metric_type: counter
      help: "Number of ratelimit gRPC requests received."

    - match: "airlock.current_requests_per_second"
      name: "airlock_microgateway_license_guard_current_requests_per_second"
      match_metric_type: gauge
      help: "An approximate sliding-window average of the combined throughput of all Airlock Microgateway Engines."

    # Performance metrics
    - match: "ratelimit_server.ShouldRateLimit.response_time"
      name: "airlock_microgateway_license_guard_response_time_seconds"
      match_metric_type: timer
      help: "Response time histogram for rate limit requests."
      observer_type: histogram

    # Error metrics
    - match: "ratelimit.service.call.should_rate_limit.*"
      name: "airlock_microgateway_license_guard_errors_total"
      match_metric_type: counter
      help: "Total number of errors of a certain type."
      labels:
        err_type: "$1"

    # Internal Ratelimit metrics
    #- match: "ratelimit.service.rate_limit.airlock-microgateway-license.*.total_hits"
    #  name: "airlock_microgateway_license_guard_requests_total"
    #  match_metric_type: counter
    #  labels:
    #    limit: $1
    #- match: "ratelimit.service.rate_limit.airlock-microgateway-license.*.within_limit"
    #  name: "airlock_microgateway_license_guard_requests_within_limit_total"
    #  match_metric_type: counter
    #  labels:
    #    limit: $1
    #- match: "ratelimit.service.rate_limit.airlock-microgateway-license.*.near_limit"
    #  name: "airlock_microgateway_license_guard_requests_near_limit_total"
    #  match_metric_type: counter
    #  labels:
    #    limit: $1
    #- match: "ratelimit.service.rate_limit.airlock-microgateway-license.*.over_limit"
    #  name: "airlock_microgateway_license_guard_requests_over_limit_total"
    #  match_metric_type: counter
    #  labels:
    #    limit: $1
    #- match: "ratelimit.service.rate_limit.airlock-microgateway-license.*.shadow_mode"
    #  name: "airlock_microgateway_license_guard_requests_over_limit_ignored_total"
    #  match_metric_type: counter
    #  labels:
    #    limit: $1

    - match: "."
      match_type: "regex"
      action: "drop"
      name: "dropped"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: airlock-microgateway-license-guard
  name: airlock-microgateway-license-guard-ratelimit-config
