apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: airlock-microgateway-license-guard
    app.kubernetes.io/version: 4.0.0
  name: airlock-microgateway-license-guard
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/name: airlock-microgateway-license-guard
      app.kubernetes.io/version: 4.0.0
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: ratelimit
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/name: airlock-microgateway-license-guard
        app.kubernetes.io/version: 4.0.0
    spec:
      containers:
        - args:
            - --web.listen-address=:9102
            - --statsd.mapping-config=/etc/statsd-exporter/conf.yaml
          image: docker.io/prom/statsd-exporter:v0.23.1@sha256:75440b4fda85e4c603baaf7fedaeeedff0dfbca943bc7bafb94ade0355a7d02d
          name: statsd-exporter
          ports:
            - containerPort: 9102
              name: metrics
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /etc/statsd-exporter/conf.yaml
              name: license-guard-ratelimit-config
              subPath: statsd.yaml
        - command:
            - /license-guard
          env:
            - name: LOG_LEVEL
              value: info
            - name: LOG_FORMAT
              value: json
            - name: USE_STATSD
              value: "true"
            - name: STATSD_PORT
              value: "9125"
            - name: GOSTATS_FLUSH_INTERVAL_SECONDS
              value: "5"
          image: docker.io/ergon/airlock-microgateway-license-guard:4.0.0@sha256:fb371377c7b37105dd1e27b9d11f144b46b5aa54cf7ff7c1c75cf97029895290
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
          name: ratelimit
          ports:
            - containerPort: 18295
              name: server
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /etc/certs
              name: airlock-microgateway-license-guard-cert
              readOnly: true
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 10
      volumes:
        - configMap:
            name: airlock-microgateway-license-guard-ratelimit-config
          name: license-guard-ratelimit-config
        - name: airlock-microgateway-license-guard-cert
          secret:
            secretName: airlock-microgateway-license-guard-cert
