apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: airlock-microgateway-operator
    app.kubernetes.io/version: 4.0.0-beta1
    control-plane: airlock-microgateway-operator
  name: airlock-microgateway-operator-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: airlock-microgateway-operator
      app.kubernetes.io/version: 4.0.0-beta1
      control-plane: airlock-microgateway-operator
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: airlock-microgateway-operator
        app.kubernetes.io/version: 4.0.0-beta1
        control-plane: airlock-microgateway-operator
    spec:
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
        - args:
            - --config=operator_config.yaml
          command:
            - /manager
          env:
            - name: NETWORK_MANAGER_IMAGE
              value: docker.io/ergon/airlock-microgateway-network-manager:4.0.0-beta1@sha256:05cd4474ab5fef6d9106efc665f5c0476e7486496b39bc10daec9476c2087ff6
            - name: ENGINE_IMAGE
              value: docker.io/ergon/airlock-microgateway-engine:4.0.0-beta1@sha256:d280af64fcb047c8d932fdbb211b46cc46b0b7f2cd88a289fe63f86dd53174d3
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WATCH_NAMESPACE
              value: ""
          image: docker.io/ergon/airlock-microgateway-operator:4.0.0-beta1@sha256:970bee29eebac12c9bf0b65bf768c7a81fa1521e17911b56872eb64020935403
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            - containerPort: 13377
              name: xds-server
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
            - mountPath: /opt/airlock/license/
              name: airlock-microgateway-license
              readOnly: true
            - mountPath: /operator_config.yaml
              name: operator-config
              subPath: operator_config.yaml
            - mountPath: /sidecar/engine_container_template.yaml
              name: operator-config
              subPath: engine_container_template.yaml
            - mountPath: /sidecar/network_manager_container_template.yaml
              name: operator-config
              subPath: network_manager_container_template.yaml
            - mountPath: /engine_bootstrap_config_template.yaml
              name: operator-config
              subPath: engine_bootstrap_config_template.yaml
      securityContext:
        runAsNonRoot: true
      serviceAccountName: airlock-microgateway-operator-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
        - name: airlock-microgateway-license
          secret:
            defaultMode: 292
            optional: true
            secretName: airlock-microgateway-license
        - configMap:
            name: airlock-microgateway-operator-operator-config
          name: operator-config
