apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: airlock-microgateway-license-guard
    app.kubernetes.io/version: 4.0.2
  name: airlock-microgateway-license-guard
spec:
  ports:
    - appProtocol: grpc
      name: ratelimit
      port: 13378
      protocol: TCP
      targetPort: 18295
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: airlock-microgateway-license-guard
    app.kubernetes.io/version: 4.0.2
  type: ClusterIP
