apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: airlock-microgateway-operator
    app.kubernetes.io/version: 4.1.7
  name: airlock-microgateway-operator-serving-cert
spec:
  dnsNames:
    - airlock-microgateway-operator-webhook.OPERATOR_NAMESPACE.svc
    - airlock-microgateway-operator-webhook.OPERATOR_NAMESPACE.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: airlock-microgateway-operator-selfsigned-issuer
  secretName: webhook-server-cert
