apiVersion: v1
data:
  redis.conf: |-
    port 0
    tls-port 6379
    tls-cert-file /etc/certs/server.crt
    tls-key-file /etc/certs/server.key
    tls-ca-cert-file /etc/certs/ca.crt
    tls-auth-clients no
    tls-protocols "TLSv1.3"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: airlock-microgateway-license-guard
    app.kubernetes.io/version: 4.1.4
  name: airlock-microgateway-license-guard-redis-config
