apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: airlock-microgateway-operator
    app.kubernetes.io/version: 4.1.3
    control-plane: airlock-microgateway-operator
  name: airlock-microgateway-operator-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: airlock-microgateway-operator
      control-plane: airlock-microgateway-operator
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: airlock-microgateway-operator
        app.kubernetes.io/version: 4.1.3
        control-plane: airlock-microgateway-operator
    spec:
      containers:
        - args:
            - --config=operator_config.yaml
          env:
            - name: ENGINE_IMAGE
              value: docker.io/ergon/airlock-microgateway-engine:4.1.3@sha256:c19e7ce7c4295e9df4c5c9712bbf15c1d2d70ca4336787dc73bc6d9f90274eae
            - name: NETWORK_VALIDATOR_IMAGE
              value: busybox:1.36.1-musl@sha256:0f287c70d4bda87a5b1ea97831c4b0f8b7c2b7c87279c0dc673b1ec600f40854
            - name: OPERATOR_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/ergon/airlock-microgateway-operator:4.1.3@sha256:35339b64116583b44ddb7203cba33a53c622d97b2df2e99b39b4e982b2a8704c
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            - containerPort: 13377
              name: xds-server
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
            - mountPath: /opt/airlock/license/
              name: airlock-microgateway-license
              readOnly: true
            - mountPath: /operator_config.yaml
              name: operator-config
              subPath: operator_config.yaml
            - mountPath: /sidecar/engine_container_template.yaml
              name: operator-config
              subPath: engine_container_template.yaml
            - mountPath: /sidecar/network_validator_container_template.yaml
              name: operator-config
              subPath: network_validator_container_template.yaml
            - mountPath: /engine_bootstrap_config_template.yaml
              name: operator-config
              subPath: engine_bootstrap_config_template.yaml
      securityContext:
        runAsNonRoot: true
      serviceAccountName: airlock-microgateway-operator-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
        - name: airlock-microgateway-license
          secret:
            defaultMode: 292
            optional: true
            secretName: airlock-microgateway-license
        - configMap:
            name: airlock-microgateway-operator-operator-config
          name: operator-config
