apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: airlock-microgateway-license-guard
    app.kubernetes.io/version: 4.1.4
  name: airlock-microgateway-license-guard
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/name: airlock-microgateway-license-guard
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: ratelimit
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/name: airlock-microgateway-license-guard
        app.kubernetes.io/version: 4.1.4
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: server
                    app.kubernetes.io/name: airlock-microgateway-license-guard
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - command:
            - /license-guard
          env:
            - name: LOG_LEVEL
              value: info
            - name: LOG_FORMAT
              value: json
            - name: USE_STATSD
              value: "true"
            - name: STATSD_PORT
              value: "9125"
            - name: GOSTATS_FLUSH_INTERVAL_SECONDS
              value: "5"
          image: docker.io/ergon/airlock-microgateway-license-guard:4.1.4@sha256:86c5ea4d55d406841340424d7546c465b1dacf38d9b1490d128812058f268e9c
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
          name: ratelimit
          ports:
            - containerPort: 18295
              protocol: TCP
            - containerPort: 9102
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /etc/certs
              name: airlock-microgateway-license-guard-cert
              readOnly: true
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 10
      volumes:
        - name: airlock-microgateway-license-guard-cert
          secret:
            secretName: airlock-microgateway-license-guard-cert
