source:
  kind: Namespace
  fieldPath: metadata.name
targets:
  - select:
      kind: Certificate
      name: airlock-microgateway-operator-serving-cert
    fieldPaths:
      - spec.dnsNames.0
      - spec.dnsNames.1
    options:
      delimiter: '.'
      index: 1
  - select:
      kind: ValidatingWebhookConfiguration
    fieldPaths:
      - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: '/'
      index: 0
  - select:
      kind: ValidatingWebhookConfiguration
    fieldPaths:
      - metadata.name
    options:
      delimiter: '-'
      index: 4
  - select:
      kind: ValidatingWebhookConfiguration
    fieldPaths:
      - webhooks.*.clientConfig.service.namespace
  - select:
      kind: MutatingWebhookConfiguration
    fieldPaths:
      - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: '/'
      index: 0
  - select:
      kind: MutatingWebhookConfiguration
    fieldPaths:
      - metadata.name
    options:
      delimiter: '-'
      index: 4
  - select:
      kind: MutatingWebhookConfiguration
    fieldPaths:
      - webhooks.*.clientConfig.service.namespace
  - select:
      kind: ClusterRole
      name: airlock-microgateway-operator-manager-ns
    fieldPaths:
      - metadata.name
    options:
      delimiter: '-'
      index: 4
  - select:
      kind: ClusterRoleBinding
      name: airlock-microgateway-operator-manager-ns
    fieldPaths:
      - metadata.name
    options:
      delimiter: '-'
      index: 4
  - select:
      kind: ClusterRole
      name: airlock-microgateway-operator-proxy-ns
    fieldPaths:
      - metadata.name
    options:
      delimiter: '-'
      index: 4
  - select:
      kind: ClusterRoleBinding
      name: airlock-microgateway-operator-proxy-ns
    fieldPaths:
      - metadata.name
    options:
      delimiter: '-'
      index: 4
