apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: airlock-microgateway-operator
    app.kubernetes.io/version: 4.1.1
  name: airlock-microgateway-operator-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airlock-microgateway-operator-leader-election
subjects:
  - kind: ServiceAccount
    name: airlock-microgateway-operator-controller-manager
