# This patch injects the 'sidecar.microgateway.airlock.com/inject: "true"' annotation into the deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    metadata:
      labels:
        sidecar.microgateway.airlock.com/inject: "true"