# This patch injects the 'k8s.v1.cni.cncf.io/network: "<airlock-cni-network-attachment-definition>"' annotation into the deployment
# required on openshift
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: default/airlock-microgateway-cni
