# This patch injects the 'sidecar.microgateway.airlock.com/inject: "true"' annotation into the deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    metadata:
      annotations:
        sidecar.microgateway.airlock.com/inject: "true"
        sidecar.microgateway.airlock.com/engineLogLevel: "trace"
        k8s.v1.cni.cncf.io/networks: default/airlock-microgateway-cni # required on openshift
