{{- if .Values.licenseGuard.serviceMonitor.create }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "airlock-microgateway.license-guard.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airlock-microgateway.license-guard.labels" . | nindent 4 }}
    {{- with .Values.licenseGuard.serviceMonitor.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "airlock-microgateway.license-guard.selectorLabels" . | nindent 6 }}
  endpoints:
    - path: /metrics
      port: metrics
      scheme: http
{{- end -}}