apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: nginxinc/nginx-unprivileged:1.23-alpine
          name: nginx
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            capabilities:
              drop: [ "ALL" ]
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: config-include-volume
              mountPath: /etc/nginx/conf.d
              readOnly: true
            - name: server-config-include-volume
              mountPath: /etc/nginx/server.conf.d
              readOnly: true
            - name: run
              mountPath: /var/run/
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config
        - name: config-include-volume
          configMap:
            name: nginx-default-config
        - name: server-config-include-volume
          configMap:
            name: nginx-server-config
        - name: run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
