resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: nginx-config
  files:
  - nginx.conf
- name: nginx-default-config
  files:
  - default.conf
- name: nginx-server-config
  files:
    - common.conf

generatorOptions:
  disableNameSuffixHash: true
