{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: cni-plugin
    {{- include "airlock-microgateway-cni.labels" . | nindent 4 }}
  name: {{ include "airlock-microgateway-cni.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - patch
{{- end -}}
