apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: cni-plugin-config
    {{- include "airlock-microgateway-cni.labels" . | nindent 4 }}
  name: {{ include "airlock-microgateway-cni.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  plugin-conf.json: |-
    {
      "type": "{{ include "airlock-microgateway-cni.fullname" . }}",
      "debug": {{ eq .Values.config.logLevel "debug" }},
      "logFilePath": "/var/log/{{ include "airlock-microgateway-cni.fullname" . }}.log",
      "kubernetes": {
        "kubeconfig": "{{ .Values.config.cniNetDir }}/{{ include "airlock-microgateway-cni.fullname" . }}-kubeconfig",
        "excludeNamespaces": {{ toJson .Values.config.excludeNamespaces }}
      }
    }
