{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: cni-plugin
    {{- include "airlock-microgateway-cni.labels" . | nindent 4 }}
  name: {{ include "airlock-microgateway-cni.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
