{
 "title": "Airlock Microgateway Upstream - Metrics",
 "tags": [ "airlock-microgateway" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "operator",
    "label": "Microgateway Operator",
    "query": {
     "query": "label_values(microgateway_build_info,managed_by)"
    }
   },
   {
    "name": "namespace",
    "label": "Gateway Namespace",
    "query": {
     "query": "label_values(microgateway_build_info{managed_by=~\"$operator\"},namespace)"
    }
   },
   {
    "name": "gateway_name",
    "label": "Gateway Name",
    "query": {
     "query": "label_values(microgateway_build_info{managed_by=~\"$operator\", namespace=~\"$namespace\"},gateway)"
    }
   },
   {
    "name": "backend_service",
    "label": "Backend Service",
    "query": {
     "query": "label_values(envoy_cluster_bind_errors{managed_by=~\"$operator\", namespace=~\"$namespace\", gateway=~\"$gateway_name\"},upstream)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Upstream Request Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "description": "Total number of requests from Airlock Microgateway to application upstreams.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum (increase(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[$__range])))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Request Error Rate",
   "type": "stat",
   "description": "Percentage of 4xx and 5xx upstream requests.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`, envoy_response_code=~\"[45]..\"}[$__range]))/\nsum (increase(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[$__range]))",
     "legendFormat": "Request Error Rate"
    }
   ]
  },
  {
   "title": "1xx Requests",
   "type": "stat",
   "description": "Number of requests with a 1xx response code from application upstreams.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum (increase(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`, envoy_response_code=~\"1..\"}[$__range])) or on () vector(0))",
     "legendFormat": "Total 1xx Requests"
    }
   ]
  },
  {
   "title": "2xx Requests",
   "type": "stat",
   "description": "Number of requests with a 2xx response code from application upstreams.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum (increase(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`, envoy_response_code=~\"2..\"}[$__range])))",
     "legendFormat": "Total 2xx Requests"
    }
   ]
  },
  {
   "title": "3xx Requests",
   "type": "stat",
   "description": "Number of requests with a 3xx response code from application upstreams.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum (increase(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`, envoy_response_code=~\"3..\"}[$__range])))",
     "legendFormat": "Total 3xx Requests"
    }
   ]
  },
  {
   "title": "4xx Requests",
   "type": "stat",
   "description": "Number of requests with a 4xx response code from application upstreams.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`, envoy_response_code=~\"4..\"}[$__range])))",
     "legendFormat": "Total 4xx Requests"
    }
   ]
  },
  {
   "title": "5xx Requests",
   "type": "stat",
   "description": "Number of requests with a 5xx response code from application upstreams.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum (increase(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`, envoy_response_code=~\"5..\"}[$__range])))",
     "legendFormat": "Total 5xx Requests"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "description": "Total requests per second to upstream applications.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[1m]))",
     "legendFormat": "Requests per second"
    },
    {
     "expr": "sum (rate(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`, envoy_response_code=~\"[45]..\"}[$__rate_interval]))/\nsum (rate(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[1m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "description": "Percentiles of the application upstream latency over one minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum(rate(envoy_cluster_upstream_rq_time_bucket{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[1m])) by (le))",
     "legendFormat": "25th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[1m])) by (le))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[1m])) by (le))",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "1xx Requests",
   "type": "timeseries",
   "description": "Requests per second to upstream applications by their actual response code (1xx).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum  by (envoy_response_code) (rate(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`, envoy_response_code=~\"1..\"}[1m]))",
     "legendFormat": "1xx Requests per second"
    }
   ]
  },
  {
   "title": "3xx Requests",
   "type": "timeseries",
   "description": "Requests per second to upstream applications by their actual response code (3xx).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum  by (envoy_response_code) (rate(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`, envoy_response_code=~\"3..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2xx Requests",
   "type": "timeseries",
   "description": "Requests per second to upstream applications by their actual response code (2xx).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum  by (envoy_response_code) (rate(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`, envoy_response_code=~\"2..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx Requests",
   "type": "timeseries",
   "description": "Requests per second to upstream applications by their actual response code (4xx).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum  by (envoy_response_code) (rate(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`, envoy_response_code=~\"4..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Requests",
   "type": "timeseries",
   "description": "Requests per second to upstream applications by their actual response code (5xx).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum  by (envoy_response_code) (rate(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`, envoy_response_code=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream TLS Connection Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }
  },
  {
   "title": "TLS Connection Handshakes",
   "type": "stat",
   "description": "Number of successful TLS handshakes to upstream backends.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(envoy_cluster_ssl_handshake{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[$__range])))",
     "legendFormat": "TLS Connection Handshakes"
    }
   ]
  },
  {
   "title": "TLS Connection Error Rate",
   "type": "stat",
   "description": "Percentage of TLS connection errors to upstream backends (does not include failed certificate verifications).",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(envoy_cluster_ssl_connection_error{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[$__range]))/\nsum (increase(envoy_cluster_ssl_handshake{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[$__range]))",
     "legendFormat": "TLS Connection Error Rate"
    }
   ]
  },
  {
   "title": "TLS Connection Errors",
   "type": "stat",
   "description": "Number of TLS connection errors to upstream backends (does not include failed certificate verifications).",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum (increase(envoy_cluster_ssl_connection_error{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[$__range])))",
     "legendFormat": "TLS Connection errors"
    }
   ]
  },
  {
   "title": "TLS Connections",
   "type": "timeseries",
   "description": "TLS connection handshakes and number of TLS connection errors per second.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ssl_handshake{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[1m]))",
     "legendFormat": "TLS handshakes per second"
    },
    {
     "expr": "sum(rate(envoy_cluster_ssl_connection_error{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[1m]))",
     "legendFormat": "TLS connection errors per second"
    }
   ]
  },
  {
   "title": "TLS Protocols",
   "type": "barchart",
   "description": "TLS protocols by versions used in successful TLS connections.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (envoy_ssl_version) (increase(envoy_cluster_ssl_versions{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", upstream=~`${backend_service:regex}`}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TLS Signature Algorithms",
   "type": "barchart",
   "description": "TLS signature algorithms used in successful TLS connections.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by (envoy_ssl_sigalg) (increase(envoy_cluster_ssl_sigalgs{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TLS Ciphers",
   "type": "barchart",
   "description": "TLS ciphers used in successful TLS connections.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by (cipher_suite) (increase(envoy_cluster_ssl_ciphers{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TLS Supported Groups",
   "type": "barchart",
   "description": "TLS supported groups used in successful TLS connections.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by (envoy_ssl_curve) (increase(envoy_cluster_ssl_curves{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Upstream Connection Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Connections",
   "type": "stat",
   "description": "Number of newly established connections towards upstream applications.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(envoy_cluster_upstream_cx_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[$__range])))",
     "legendFormat": "Total Connections"
    }
   ]
  },
  {
   "title": "Failed Connections",
   "type": "stat",
   "description": "Number of failed connections towards upstream applications.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(envoy_cluster_upstream_cx_connect_fail{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[$__range])))",
     "legendFormat": "Total Failed Connections"
    }
   ]
  },
  {
   "title": "Data sent",
   "type": "stat",
   "description": "Total amount of data sent to upstream applications.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_cx_tx_bytes_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[$__range]))",
     "legendFormat": "Data sent"
    }
   ]
  },
  {
   "title": "Data received",
   "type": "stat",
   "description": "Total amount of data received by Airlock Microgateway from upstream applications.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_cx_rx_bytes_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[$__range]))",
     "legendFormat": "Data received"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Number of newly established connections per second to upstream applications.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[1m]))",
     "legendFormat": "Connections per second"
    }
   ]
  },
  {
   "title": "Failed Connections",
   "type": "timeseries",
   "description": "Number of failed connections per second to upstream applications.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_connect_fail{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[1m]))",
     "legendFormat": "Failed Connections per second"
    }
   ]
  },
  {
   "title": "Data sent",
   "type": "timeseries",
   "description": "Rate of traffic sent to upstream applications.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_tx_bytes_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[1m]))",
     "legendFormat": "Data sent"
    }
   ]
  },
  {
   "title": "Data received",
   "type": "timeseries",
   "description": "Rate of traffic received from upstream applications.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_rx_bytes_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[1m]))",
     "legendFormat": "Data received"
    }
   ]
  },
  {
   "title": "Connection Length",
   "type": "timeseries",
   "description": "Histogram on the duration of connections to upstream applications.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum(rate(envoy_cluster_upstream_cx_length_ms_bucket{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[1m])) by (le))",
     "legendFormat": "25th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_cx_length_ms_bucket{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[1m])) by (le))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_cx_length_ms_bucket{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[1m])) by (le))",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "Time to Connect",
   "type": "timeseries",
   "description": "Histogram on time to connect to upstream applications.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum(rate(envoy_cluster_upstream_cx_connect_ms_bucket{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[1m])) by (le))",
     "legendFormat": "25th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_cx_connect_ms_bucket{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[1m])) by (le))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_cx_connect_ms_bucket{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^service/.+`,upstream=~`${backend_service:regex}`}[1m])) by (le))",
     "legendFormat": "95th Percentile"
    }
   ]
  }
 ]
}