apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: airlock-microgateway-cosign-public-key
  files:
  - cosign.pub
