apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

helmCharts:
- name: airlock-microgateway-cni
  releaseName: airlock-microgateway-cni
  namespace: kube-system
  valuesFile: ./values.yaml
